### ISSUE TITLE
 SHS dataset and test value

### ISSUE THREAD

**Issue by xz-j** [Orfium/bytecover#2]
Hello：
Thank you very much for providing the code.
May I ask if it is possible for you to provide the audio data for SHS? Because many of the links in the SHS dataset are no longer valid, it is difficult to download a comprehensive set of data.
Also, could you please tell me the map value of your model on your test set?

**Comment by petvav** [comment]
Hello @xz-j

Unfortunately, I can't provide the audio data because of legal copyright issues. I had the same problem with URLs that were valid no more, this is why I have provided the training splits in order to download those that were available at the time, and not the whole SHS dataset. Note that it is possible for some URLs to not work now, because videos may become unavailable. 

In the test set the map value is 0.33.

**Comment by TeresaTsang** [comment]
> Hello @xz-j
> 
> Unfortunately, I can't provide the audio data because of legal copyright issues. I had the same problem with URLs that were valid no more, this is why I have provided the training splits in order to download those that were available at the time, and not the whole SHS dataset. Note that it is possible for some URLs to not work now, because videos may become unavailable.
> 
> In the test set the map value is 0.33.

Hello, petvav,

Because it takes much to download all the songs in the dataset? Could you please provide the preprocessed CQT feature files instead? 

Thanks!

**Comment by petvav** [comment]
Hello @TeresaTsang,

Sorry for the late response, but we were examining the possibility of providing the CQT features. However, we can't provide them either, because the audio can be reconstructed using the inverse algorithm, which poses potential legal copyright issues.

**Comment by AndyGuo1** [comment]
> Hello @TeresaTsang,
> 
> Sorry for the late response, but we were examining the possibility of providing the CQT features. However, we can't provide them either, because the audio can be reconstructed using the inverse algorithm, which poses potential legal copyright issues.

Hello, petvav,
do I need to download all the songs to the local through the url and then extract the characteristics of each song? Is there any other way to get the CQT characteristics of all songs
